### ISSUE TITLE
Add a section "Spell of the day"

### ISSUE THREAD

**Issue by d-coder111** [d-coder111/The-Wizards-Sorting-Hat#15]
add a button to show a random spell of the day from harry potter.

**Comment by Shreyash2001** [comment]
I will add a button on clicking will show random spells with some animations. Assign this to me

**Comment by d-coder111** [comment]
sure👍..good luck😊.

**Comment by Buddha-11** [comment]
Hey @d-coder111 the previous assignee has not moved forward with the issue for 4 days , I would like to work on this can you assign this to me instead

**Comment by d-coder111** [comment]
Hey @Buddha-11 , the previous assignee has done the required work, if you want to make changes then pls check this one #55 or you can come up with better idea or design.
