### ISSUE TITLE
Create Code_Of_Conduct.md

### ISSUE THREAD

**Issue by KirtiPratihar** [d-coder111/The-Wizards-Sorting-Hat#24]
@d-coder111 I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext, hacktoberfest Labels.

Thanks

**Comment by d-coder111** [comment]
ok @KirtiPratihar ..I will add hacktoberfest Label.

**Comment by KirtiPratihar** [comment]
@d-coder111 can you share you email id for the report management in the Code of conduct

**Comment by d-coder111** [comment]
> @d-coder111 can you share you email id for the report management in the Code of conduct

sure, divy777888@gmail.com
