### ISSUE TITLE
Can I add new questions to it

### ISSUE THREAD

**Issue by Nilam-Kumari-Mahato** [d-coder111/The-Wizards-Sorting-Hat#41]
Can I add new questions to the index.html
Please assign me this under hacktoberfest

**Comment by d-coder111** [comment]
> Can I add new questions to the index.html Please assign me this under hacktoberfest

Hey @Nilam-Kumari-Mahato do you want to contribute for hacktoberfest then pls check this one-https://github.com/d-coder111/SpectrumOfPython. If you have a python related game,machine learning project or data science.

But for this repo, I don't want to increase the number of questions.

**Comment by Nilam-Kumari-Mahato** [comment]
Ok. Thank you
