### ISSUE TITLE
Massive design change

### ISSUE THREAD

**Issue by alexwastaken** [d-coder111/The-Wizards-Sorting-Hat#56]
I made a bunch of big changes to the site as you can see below. Please assign this to me with labels and I will PR the changes. A lot of code was changed so code review might be extensive + follow up required.

[2024-10-07 16-25-30.webm](https://github.com/user-attachments/assets/7f249532-17c9-494c-b062-843b3c983bde)

Thanks!

**Comment by d-coder111** [comment]
Hey @alexwastaken, could you place the 'spell of the day' section at the end as a standalone and add some creativity to it? Everything else looks fantastic, and I'll go ahead and merge it once that's done!👍..Also do check #55 issue, if there's anything you would like to contribute..like the shape of the question box or any better idea.

Any meaningful contribution or idea is welcomed😊🎉.. happy coding.. happy learning ✌️.
