### ISSUE TITLE
Detailed House Descriptions: Provide descriptions for each house after the user is sorted.

### ISSUE THREAD

**Issue by d-coder111** [d-coder111/The-Wizards-Sorting-Hat#6]

**Comment by mahenoorsalat** [comment]
I would like to work on this issue... Assign me this issue

Looking forward to your response

Thank you Ping @d-coder111

**Comment by harshitkumargupta** [comment]
Hi @d-coder111 
Can you please assign me with this issue or any other issue with Hacktoberfest tag .  I would love to make contributions to it.
Looking forward for your response .
Thank you
