### ISSUE TITLE
Implement Spells Section

### ISSUE THREAD

**Issue by iamDyeus** [d-coder111/The-Wizards-Sorting-Hat#77]
I'd like to work on the Spells section, which will include a 'Spell of the Day' feature, while keeping the design creatively laid out.

If you have any suggestions or UI mockups, please share them so I can start working on this issue!

**Comment by d-coder111** [comment]
Hey @iamDyeus, thanks for showing interest in the project! The spells section is already in place. If you come up with a better design that matches the website's overall vibe, I'll review it and consider merging your PR. However, if it doesn’t align well, I won’t be accepting the changes.
