### ISSUE TITLE
Sound Effects: Add sound effects to enhance the overall user experience.

### ISSUE THREAD

**Issue by d-coder111** [d-coder111/The-Wizards-Sorting-Hat#8]

**Comment by mahenoorsalat** [comment]
I would like to work on this issue... Assign me this issue

Looking forward to your response

Thank you Ping @d-coder111

**Comment by d-coder111** [comment]
Great😊👍..Kindly add your name in the contributors list once you are done making the necessary changes and consider starring the repository to show your support🌟👍. Any meaningful contributions are welcomed!😊✨..good luck🚀

**Comment by harshitkumargupta** [comment]
Hey , Please assign this issue to me
