### ISSUE TITLE
Theme Options: Allow users to select different themes for the quiz interface.

### ISSUE THREAD

**Issue by d-coder111** [d-coder111/The-Wizards-Sorting-Hat#9]

**Comment by LoayTarek5** [comment]
Hi @d-coder111, @D-Binara  i hope you are doing well,
i like to contribute  and solve this issue
Could you assign it to me?

**Comment by d-coder111** [comment]
Hey @LoayTarek5 👋, I have assigned this to you..good luck in making it a better project👍🚀.

**Comment by LoayTarek5** [comment]
@d-coder111 Okay, thanks. I will do my best.

**Comment by LoayTarek5** [comment]
Hi @d-coder111 can you tell me please more by what do you mean "select different themes for the quiz interface"
do you like to add options theme here
and after choose the theme the colors of  the quiz interface part will change
![image](https://github.com/user-attachments/assets/7c9cb240-145a-4d2f-a238-c45f7ed62eab)

**Comment by d-coder111** [comment]
Hi @LoayTarek5, yes by themes I mean options but those have have to be harry potter themes only.

**Comment by LoayTarek5** [comment]
@d-coder111 Do you mean that it should be one theme only

**Comment by d-coder111** [comment]
> @d-coder111 Do you mean that it should be one theme only

No, different themes should revolve around harry potter.

**Comment by LoayTarek5** [comment]
Ahh ok, i got it
sorry for confusion


> > @d-coder111 Do you mean that it should be one theme only
> 
> No, different themes should revolve around harry potter.

**Comment by LoayTarek5** [comment]
@d-coder111 when i make PR which branch should i push to it (main or edit)
consider that I am from **hacktoberfest**

**Comment by d-coder111** [comment]
> @d-coder111 when i make PR which branch should i push to it (main or edit) consider that I am from **hacktoberfest**

main
